server:
  port: 9005
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: crawler-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: 'optional:configserver:'
  neo4j:
    authentication:
      username: neo4j
      password: password
    uri: bolt://hypercrawler-neo4j:7687

  cloud:
    config:
      enabled: true
      uri: ${CONFIG_SERVICE_URL:http://localhost:9001}
      fail-fast: false
      retry:
        max-attempts: 20
        max-interval: 10000
        initial-interval: 3000
        multiplier: 1.3
    function:
      definition: crawl|postProcess
    stream:
      rabbit:
        bindings:
          crawl-in-0:
            consumer:
              max-priority: 10
      bindings:
        crawl-in-0:
          destination: address-prioritized
          group: ${spring.application.name}
        crawl-out-0:
          destination: address-crawled
  rabbitmq:
    host: hypercrawler-rabbitmq
    port: 5672
    username: admin
    password: admin
    connection-timeout: 5s

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

  level:
    org:
      springframework:
        data:
          neo4j: DEBUG


hypercrawler:
  crawler-service:
    client:
      manager-service-uri: ${MANAGER_SERVICE_URI:http://localhost:9003}

info:
  system: hypercrawler

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}