apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-service
  labels:
    app: crawler-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler-service
  template:
    metadata:
      labels:
        app: crawler-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9005"
    spec:
      containers:
        - name: crawler-service
          image: crawler-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9005
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:9000/eureka/
            - name: CONFIG_SERVICE_URL
              value: http://config-service:9001/
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9005
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9005
            initialDelaySeconds: 5
            periodSeconds: 15