apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  labels:
    app: crawler-service
spec:
  type: ClusterIP
  selector:
    app: crawler-service
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005